server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://svc.gksl2.cloudtype.app:32564/flow
    username: admin_k
    password: admin_k

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true  # JPA에서 발생하는 쿼리문을 보여주는 콘솔창에 출력
        format_sql: true # SQL 문장이 한 줄에 나오는 것이 아니라 예쁘게 나옴!

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: info # JPA에서 발생하는 쿼리문을 로그파일로 보여주는 옵션.
  org.hibernate.type:
    descriptor.sql: trace # SQL 문에서 바인딩 되는 파라미터 값까지 보여주는 옵션